export const categoryData = {
  shops: [
    { id: "auto-dealer", label: "Auto Dealer" },
    { id: "spare-parts", label: "Spare Parts Seller" },
    { id: "car-broker", label: "Car Broker" },
    { id: "land-broker", label: "Land Broker" },
    { id: "electronics-store", label: "Electronics Store" },
    { id: "mobile-shop", label: "Mobile Shop" },
    { id: "medical-store", label: "Medical Store" },
    { id: "grocery-store", label: "Grocery Store" },
    { id: "fashion-boutique", label: "Fashion Boutique" },
    { id: "furniture-shop", label: "Furniture Shop" },
    { id: "hardware-store", label: "Hardware Store" },
    { id: "tyre-shop", label: "Tyre Shop" },
    { id: "bike-showroom", label: "Bike Showroom" },
    { id: "car-showroom", label: "Car Showroom" },
    { id: "building-material", label: "Building Material" },
    { id: "jewellery-shop", label: "Jewellery Shop" },
    { id: "book-store", label: "Book Store" },
    { id: "sweet-shop", label: "Sweet Shop" },
    { id: "restaurant", label: "Restaurant" },
    { id: "bakery", label: "Bakery" }
  ],

  services: [
    { id: "car-repair", label: "Car Repair Service" },
    { id: "bike-mechanic", label: "Bike Mechanic" },
    { id: "ac-repair", label: "AC Repair" },
    { id: "electrician", label: "Electrician" },
    { id: "plumber", label: "Plumber" },
    { id: "interior-designer", label: "Interior Designer" },
    { id: "digital-marketing", label: "Digital Marketing Agency" },
    { id: "event-planner", label: "Event Planner" },
    { id: "photographer", label: "Photographer" },
    { id: "real-estate-consultant", label: "Real Estate Consultant" },
    { id: "security-service", label: "Security Service" },
    { id: "house-cleaning", label: "House Cleaning" },
    { id: "water-supplier", label: "Water Supplier" },
    { id: "transport-service", label: "Transport Service" },
    { id: "logistics-provider", label: "Logistics Provider" },
    { id: "internet-provider", label: "Internet Service Provider" },
    { id: "courier-service", label: "Courier Service" },
    { id: "travel-agency", label: "Travel Agency" },
    { id: "gym-trainer", label: "Gym Trainer" },
    { id: "consultant", label: "Consultant" }
  ],

  jobs: [
    { id: "retail-hiring", label: "Retail Hiring" },
    { id: "factory-hiring", label: "Factory Hiring" },
    { id: "driver-hiring", label: "Driver Hiring" },
    { id: "sales-executive", label: "Sales Executive" },
    { id: "office-staff", label: "Office Staff" },
    { id: "manager-hiring", label: "Manager Hiring" },
    { id: "helper-hiring", label: "Helper Hiring" },
    { id: "delivery-executive", label: "Delivery Executive" },
    { id: "field-executive", label: "Field Executive" },
    { id: "technician-hiring", label: "Technician Hiring" },
    { id: "security-guard", label: "Security Guard" },
    { id: "receptionist", label: "Receptionist" },
    { id: "accountant", label: "Accountant" },
    { id: "marketing-staff", label: "Marketing Staff" },
    { id: "warehouse-staff", label: "Warehouse Staff" },
    { id: "supervisor", label: "Supervisor" },
    { id: "teacher-hiring", label: "Teacher Hiring" },
    { id: "hospital-staff", label: "Hospital Staff" },
    { id: "construction-worker", label: "Construction Worker" },
    { id: "hr-hiring", label: "HR Hiring" }
  ],

  "buy-sell": [
    { id: "used-cars", label: "Used Cars" },
    { id: "used-bikes", label: "Used Bikes" },
    { id: "property-sale", label: "Property Sale" },
    { id: "land-sale", label: "Land Sale" },
    { id: "electronics-resale", label: "Electronics Resale" },
    { id: "furniture-resale", label: "Furniture Resale" },
    { id: "mobile-resale", label: "Mobile Resale" },
    { id: "home-appliances", label: "Home Appliances" },
    { id: "farm-equipment", label: "Farm Equipment" },
    { id: "construction-equipment", label: "Construction Equipment" },
    { id: "rental-property", label: "Rental Property" },
    { id: "vehicle-rental", label: "Vehicle Rental" },
    { id: "second-hand-goods", label: "Second Hand Goods" },
    { id: "old-machinery", label: "Old Machinery" },
    { id: "commercial-property", label: "Commercial Property" },
    { id: "plot-sale", label: "Plot Sale" },
    { id: "flat-sale", label: "Flat Sale" },
    { id: "agricultural-land", label: "Agricultural Land" },
    { id: "shop-sale", label: "Shop Sale" },
    { id: "office-space-sale", label: "Office Space Sale" }
  ]
} as const;

export type MainCategory = keyof typeof categoryData;
export type SubCategory = typeof categoryData[MainCategory][number];
