export const SEO_LIBRARY = {
  "Plumber": [
    "Best Plumber in Korba", "Emergency Plumbing 24/7", "Water Tank Cleaning Korba",
    "Bathroom Pipe Leakage Repair", "Toilet Seat Installation", "Kitchen Sink Repair",
    "Gyser Installation Korba", "Low Water Pressure Fix", "Drainage Cleaning Service",
    "Industrial Plumbing Korba", "CPVC Pipe Fitting", "Taps and Faucets Repair",
    "Submersible Pump Repair", "Bathroom Renovation Plumber", "Home Maintenance Korba",
    "Sanitary Ware Installation", "Garden Pipe Fitting", "Pipe Blockage Solution",
    "Residential Plumber Korba", "Urgent Pipe Repair", "Valve Replacement",
    "New House Plumbing Setup", "Commercial Plumbing Service", "Leak Detection Specialist",
    "Local Plumber Near Me", "Korba City Plumbing Expert", "Affordable Plumber",
    "Modern Pipe Fitters", "PVC Pipe Joint Repair", "Water Line Installation",
    "Toilet Flush Repair", "Shower Repair Service", "Plumbing Contractor Korba",
    "Solar Geyser Service", "Roof Tank Fitting", "Internal Pipe Fitting",
    "External Drainage Layout", "Septic Tank Expert", "Hand Pump Repair",
    "Plumbing Inspection Service", "Smart Bathroom Setup", "Grohe Fitting Expert",
    "Jaquar Fitting Specialist", "Bathroom Leakage Expert", "Floor Trap Cleaning",
    "Plumbing Materials Consultant", "Heavy Duty Pipe Repair", "Construction Plumber",
    "Maintenance Contract (AMC)", "Rapid Response Plumber", "Professional Pipe Doctor"
  ],
  "Doctor/Clinic": [
    "Best Clinic in Korba", "Emergency Doctor Near Me", "Top General Physician",
    "Pediatrician Korba", "Gynecologist Services", "Best Dentist in Korba",
    "24 Hours Medical Help", "Skin Specialist Korba", "Dermatology Clinic",
    "Online Doctor Consultation", "Vaccination Center Korba", "Sugar & BP Checkup",
    "Pathology Lab Integration", "Home Visit Doctor", "Orthopedic Surgeon",
    "Neurologist in Korba", "Heart Specialist", "Chest Physician",
    "ENT Specialist Korba", "Eye Hospital Services", "Laser Eye Surgery",
    "Physiotherapy Center", "Weight Loss Clinic", "Child Specialist Korba",
    "Mental Health Counselor", "Psychiatrist in Korba", "Dialysis Center",
    "ICU Services Korba", "Pharmacy Attached Clinic", "X-Ray & Ultrasound",
    "Diagnostic Center", "Urologist Korba", "Thyroid Specialist",
    "Diabetes Management", "Old Age Care Clinic", "Ayurvedic Doctor Korba",
    "Homeopathy Clinic", "Pain Management Center", "Gastroenterologist",
    "Allergy Specialist", "Ear Wax Removal", "Wound Care Specialist",
    "Medical Certificates", "Health Insurance Support", "Regular Health Checkup",
    "Family Doctor Korba", "Multi-speciality Hospital", "Trauma Center",
    "Ambulance Support", "Qualified Medical Team"
  ],
  "Restaurant/Cafe": [
    "Best Restaurant in Korba", "Top Rated Cafe", "Family Dining Korba",
    "Pure Veg Restaurant", "Non-Veg Delicacies", "Fast Food Center",
    "Chinese Food Korba", "South Indian Breakfast", "North Indian Thali",
    "Biryani Special Korba", "Home Delivery Service", "Party Hall Booking",
    "Birthday Celebration Venue", "Romantic Dinner Spot", "Street Food Korba",
    "Bakery and Sweets", "Live Music Cafe", "Coffee Shop Korba",
    "Pizza Delivery Near Me", "Burger Point Korba", "Healthy Food Options",
    "Organic Cafe", "Tandoori Special", "Continental Food",
    "Italian Cuisine Korba", "Mughlai Food Expert", "Juice Center",
    "Ice Cream Parlor", "Dessert Shop Korba", "Catering Services",
    "Outdoor Seating Cafe", "Free Wi-Fi Cafe", "Midnight Food Delivery",
    "Pocket Friendly Food", "Luxury Fine Dine", "Garden Restaurant",
    "Rooftop Cafe Korba", "Traditional Chhattisgarhi Food", "Snacks Center",
    "Evening Hangout Spot", "Best Tea Point", "Sandwich Bar",
    "Pasta Specialist", "Kebab Corner", "Food Court Stall",
    "Buffet System Korba", "Corporate Lunch Venue", "Takeaway Food",
    "Hygienic Kitchen", "Custom Cake Orders"
  ],
  "Mobile/Laptop Shop": [
    "Best Mobile Shop Korba", "Laptop Repair Center", "iPhone Dealer Korba",
    "Samsung Store Near Me", "Used Mobile Buying Selling", "Mobile Accessories Store",
    "Laptop Battery Replacement", "Screen Repair Expert", "Software Installation",
    "Data Recovery Services", "Gaming Laptop Store", "Refurbished Laptops Korba",
    "Smartphone Repair 1 Hour", "Apple Service Center", "HP Dell Lenovo Dealer",
    "Windows OS Install", "MacBook Repair Korba", "Charging Port Fix",
    "Headphones and Speakers", "Smart Watch Store", "Tablets and iPads",
    "Gaming PC Builder", "Computer Hardware Shop", "Networking Solutions",
    "Antivirus Software", "Motherboard Repair", "Keyboard Mouse Store",
    "Monitor and Display Shop", "Old Laptop Exchange", "No Cost EMI Mobiles",
    "Authorized Brand Dealer", "Mobile Glass Change", "Water Damage Repair",
    "Hanging Problem Solution", "Fast Charging Adaptors", "Bluetooth Earbuds Shop",
    "Mobile Pouch and Skins", "Laptop SSD Upgrade", "RAM Expansion Service",
    "Printer Repair Korba", "Toner Refilling", "Wireless Router Setup",
    "Second Hand iPhone", "Gadget Repair Center", "Tech Support Korba",
    "Mobile Unlocking Service", "Original Battery Store", "CCTV Monitor Setup",
    "Hardware Upgrade", "Reliable Tech Shop"
  ]
};